version: "3.8"
services:
  web:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./dist/src:/app/dist/src
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    ports:
      - '3306:3306'